---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install PIP and Python dev
      apt:
        pkg={{ item }}
        state=present
        update_cache=yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - libssl-dev

    - name: Install Six
      pip:
        name=six
        version=1.10.0

    - name: Upgrade pip
      pip:
        name=pip
        state=latest

    - name: Install Request security
      pip:
        name=requests[security]
        state=latest

    - name: Install dependencies
      command: chdir=/home/vagrant/doboto make install_modules

    - name: Install DOBOTO
      command: chdir=/home/vagrant/doboto python setup.py install

    - name: Install markupsafe
      pip:
        name={{item}}
      with_items:
        - markupsafe
        - ansible
        - jmespath
