---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install PIP and Python dev
      apt:
        pkg={{ item }}
        state=present
        update_cache=yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      with_items:
        - python-pip
        - python-dev
        - libffi-dev
        - libssl-dev

    - name: Install Six
      pip:
        name=six
        version=1.10.0

    - name: Install dependencies
      command: chdir=/home/vagrant/doboto make install_modules

    - name: Install DOBOTO
      command: chdir=/home/vagrant/doboto python setup.py install

    - name: Install markupsafe
      pip:
        name=markupsafe

    - name: Install Ansible
      pip:
        name=ansible
